import NovedadItem from "@/components/NovedadItem";

export const metadata = {
    title: "Cabañas Arrayanes :: Promociones",
    description: "destacadosGenerated by create next app",
};

export default function Promociones() {
    return (
        <section className="contenedor_promociones">
            <h2>Promociones</h2>
            <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/600x400/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />
            <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/600x400/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />
            <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/600x400/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />
            <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/600x400/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />


        </section>
    )
}