
import BootstrapClient from "@/components/BootstrapClient";
import "@/styles/cabanas.css";
export const metadata = {
    title: "Cabañas Arrayanes :: Cabanas",
    description: "destacadosGenerated by create next app",
};
export default function Cabanas() {
    return (
        <>
            <div className="contenedor1_cabanas">
                <div className="cabanas_montana">
                    <img src="/Imagenes/inicio3.jpg" alt="Cabanas en la montaña" />
                    <div className="mask">
                        <h2>Cabañas Arrayanes</h2>
                        <h3>EL BOLSÓN | PATAGONIA ARGENTINA</h3>
                        <p>"Queremos ser parte de tus mejores momentos..."</p>
                    </div>
                </div>
            </div>

            <BootstrapClient />
            <div className="contenedor2_cabanas">
                <div id="carouselExampleFade" className="carousel slide carousel-fade">
                    <div className="carousel-inner">
                        <div className="carousel-item active">
                            <img src="/Imagenes/6.jpg" className="d-block w-100" alt="..." />
                        </div>
                        <div className="carousel-item">
                            <img src="/Imagenes/2.jpg" className="d-block w-100" alt="..." />
                        </div>
                        <div className="carousel-item">
                            <img src="/Imagenes/5.jpg" className="d-block w-100" alt="..." />
                        </div>
                        <div className="carousel-item">
                            <img src="/Imagenes/1-1.jpg" className="d-block w-100" alt="..." />
                        </div>
                    </div>
                    <button
                        className="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExampleFade"
                        data-bs-slide="prev"
                    >
                        <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span className="visually-hidden">Previous</span>
                    </button>
                    <button
                        className="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExampleFade"
                        data-bs-slide="next"
                    >
                        <span className="carousel-control-next-icon" aria-hidden="true"></span>
                        <span className="visually-hidden">Next</span>
                    </button>
                </div>
                <div className="item_texto">
                    <h2>Cabañas para 6 personas</h2>
                    <p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt ad dolor deleniti in architecto,
                        sapiente sit placeat, fugiat quis molestias enim inventore perspiciatis vel cumque magnam corrupti?
                        Quod, ipsa id!
                    </p>
                </div>
            </div>

            {/* Carrusel para 4 personas */}
            <div className="contenedor3_cabanas">
                <div id="carouselExample" className="carousel slide">
                    <div className="carousel-inner">
                        <div className="carousel-item active">
                            <img src="/Imagenes/8.jpg" className="d-block w-100" alt="..." />
                        </div>
                        <div className="carousel-item">
                            <img src="/Imagenes/9.jpg" className="d-block w-100" alt="..." />
                        </div>
                        <div className="carousel-item">
                            <img src="/Imagenes/10.jpg" className="d-block w-100" alt="..." />
                        </div>
                        <div className="carousel-item">
                            <img src="/Imagenes/7.jpg" className="d-block w-100" alt="..." />
                        </div>
                    </div>
                    <button
                        className="carousel-control-prev"
                        type="button"
                        data-bs-target="#carouselExample"
                        data-bs-slide="prev"
                    >
                        <span className="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span className="visually-hidden">Previous</span>
                    </button>
                    <button
                        className="carousel-control-next"
                        type="button"
                        data-bs-target="#carouselExample"
                        data-bs-slide="next"
                    >
                        <span className="carousel-control-next-icon" aria-hidden="true"></span>
                        <span className="visually-hidden">Next</span>
                    </button>
                </div>
                <div className="item_texto">
                    <h2>Cabañas para 4 personas</h2>
                    <p>
                        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Deserunt ad dolor deleniti in architecto,
                        sapiente sit placeat, fugiat quis molestias enim inventore perspiciatis vel cumque magnam corrupti?
                        Quod, ipsa id!
                    </p>
                </div>
            </div>


        </>
    );
}