import 'bootstrap/dist/css/bootstrap.min.css';

import "./globals.css";
import Nav from "../components/Nav";
import BootstrapClient from "../components/BootstrapClient";


export const metadata = {
  title: "Cabañas Arrayanes",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
     <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
      </head>    
      <body >        
        <BootstrapClient />
        <Nav />
        {children}
        <footer className="footer">
          <h4>Seguinos</h4>
          <div className="social-link">
            <a href="" target="_blank"><i className="fa-regular fa-envelope"></i></a>
            <a href="" target="_blank"><i className="fab fa-facebook"></i></a>
            <a href="" target="_blank"><i className="fab fa-instagram"></i></a>
            <a href="" target="_blank"><i className="fa-solid fa-location-dot"></i></a>
          </div>
          <br />
          <div className="logo_footer">

            <img src="Imagenes/logo2.png" width="150px" />
          </div>
          <p>Karen Rajmilchuk - AÑO 2025</p>

        </footer>
      </body>
    </html>
  );
}
