import "@/styles/promociones.css";

import NovedadItem from "@/components/NovedadItem";

export const metadata = {
    title: "Cabañas Arrayanes :: Promociones",
    description: "destacadosGenerated by create next app",
};

export default async function Promociones() {
    const data = await fetch(`${process.env.NEXT_APP_API_URL}/api/novedades`);   
    const novedades = await data.json();

    return (
        <section className="contenedor_promociones">
            <h2>Promociones</h2>
            <div className="promociones_grid">
                {/* <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/300x200/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />
                <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/300x200/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />
                <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/300x200/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" />
                <NovedadItem title="Este es el titulo de la promoción" subtitle="Subtitulo de la promoción" imagen="https://dummyimage.com/300x200/fff/aaa" body="Este es el cuerpo de la promocion.Este es el cuerpo de la promocion.Este es el cuerpo de la promocion" /> */}
                {novedades.map(item => <NovedadItem key={item.id}
                    title={item.titulo} subtitle={item.subtitulo} imagen={item.imagen} body={item.cuerpo} />)}


            </div>
        </section>
    )
}