import '../styles/normalize.css';

import 'bootstrap/dist/css/bootstrap.min.css';

import "../styles/globals.css";

import Nav from "../components/Nav";
import BootstrapClient from "../components/BootstrapClient";


export const metadata = {
  title: "Cabañas Arrayanes",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,500;1,400&family=Bungee:wght@300;400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Bungee:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />

      </head>
      <body >
        <BootstrapClient />
        <Nav />
        {children}
        <footer className="footer">
          <h4>Seguinos</h4>
          <div className="social-link">
            <a href="" target="_blank"><i className="fa-regular fa-envelope"></i></a>
            <a href="" target="_blank"><i className="fab fa-facebook"></i></a>
            <a href="" target="_blank"><i className="fab fa-instagram"></i></a>
            <a href="" target="_blank"><i className="fa-solid fa-location-dot"></i></a>
          </div>
          <br />
          <div className="logo_footer">

            <img src="Imagenes/logo2.png" width="150px" />
          </div>
          <p>Karen Rajmilchuk - AÑO 2025</p>

        </footer>
      </body>
    </html>
  );
}
