export const metadata ={
    title: "Cabañas Arrayanes :: Servicios",
    description: "destacadosGenerated by create next app",
};
export default function Servicios(){
    return (
    <section className="services">
      <h2>Nuestros Servicios</h2>
      <p>
        Vení a disfrutar de la montaña y lagos de la Comarca Andina, tenemos todo pensado para que tu estadía sea inolvidable.
      </p>

      <div className="service-grid1">
        <div className="service-item">
          <i className="fas fa-bed"></i>
          <p>Ropa blanca</p>
        </div>
        <div className="service-item">
          <i className="fas fa-wifi"></i>
          <p>WiFi</p>
        </div>
        <div className="service-item">
          <i className="fas fa-utensils"></i>
          <p>Cocina completa</p>
        </div>
        <div className="service-item">
          <i className="fas fa-broom"></i>
          <p>Limpieza diaria</p>
        </div>
      </div>

      <div className="service-grid2">
        <div className="service-item">
          <i className="fas fa-satellite-dish"></i>
          <p>DirectTV</p>
        </div>
        <div className="service-item">
          <i className="fas fa-swimming-pool"></i>
          <p>Dos piletas</p>
        </div>
        <div className="service-item">
          <i className="fas fa-tv"></i>
          <p>Smart TV 32"</p>
        </div>
        <div className="service-item">
          <i className="fas fa-sun"></i>
          <p>Solarium y reposeras</p>
        </div>
      </div>
    </section>
    );  
}

